services:
  redis:
    image: redis:8.4.0-alpine
    container_name: redis-ssl
    ports:
      - "6379:6379"
    volumes:
      - ./cache/certs:/tls
    command: >
      redis-server
      --tls-port 6379
      --port 0
      --tls-cert-file /tls/redis.crt
      --tls-key-file /tls/redis.key
      --tls-ca-cert-file /tls/redis.crt
      --tls-auth-clients no
    restart: always

  # user-api-release:
  #   build:
  #     context: ../app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   # This ensures the container restarts if it crashes
  #   restart: always

  user-api-dev:
    build:
      context: ../app
      dockerfile: Dockerfile_dev
    ports:
      - "8080:8080"
    volumes:
      - ../app:/usr/src/app
    # This ensures the container restarts if it crashes
    restart: always